In [2]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [5]:
train_labels = []
train_samples = []

In [4]:
# Example data
# 1. An expriemental drug was tested on individuals from ages 13 to 100 in a clinical trial.
# 2. The trial had 2100 participants. Half were under 65 years old.half were 65 years or older.
# 3. Around 95% of patients 65 or older exprienced side effects. 
# 4. Around 95% of patients under 65 experienced no side effects.

In [6]:
for i in range(50):
    # The 5% of the younger individuals who did expreience side effects
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(1)

    # The 5% of the younger individuals who did not expreience side effects
    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(0)

for i in range(1000):
    # The 95% of the younger individuals who did not expreience side effects
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(0)

    # The 95% of the younger individuals who did expreience side effects
    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(1)


In [9]:
train_samples
train_labels

[]

In [12]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
# shuffle function Sequence of shuffled copies of the collections.
train_labels ,train_samples = shuffle(train_labels, train_samples)

In [14]:
train_samples

array([84, 41, 43, ..., 31, 16, 73])

In [15]:
scaler  = MinMaxScaler(feature_range=(0,1))
train_samples.reshape(-1, 1)

array([[84],
       [41],
       [43],
       ...,
       [31],
       [16],
       [73]])

In [19]:
# fit_transform does not allow 1d data , so we have to reshape that
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1, 1))
scaled_train_samples

array([[0.81609195],
       [0.32183908],
       [0.34482759],
       ...,
       [0.20689655],
       [0.03448276],
       [0.68965517]])